FROM balenalib/rpi-raspbian:latest

#install python
RUN apt-get update && apt-get install -y python3 python3-pip

ENV TZ=America/New_York

RUN apt-get install -y build-essential python3-dev

RUN pip3 install pymongo

WORKDIR /app

EXPOSE 80

COPY . .

CMD ["python3", "dbtest.py"]
